### ISSUE TITLE
make script path configurable

### ISSUE THREAD

**Issue by shershen08** [vchaptsev/vue-yandex-metrika#12]
Problem description:

For some cases the other path to load script may be preferable
While path is hardcoded https://github.com/vchaptsev/vue-yandex-metrika/blob/master/src/helpers.js#L26

Suggested solution:

create config param

**Comment by vchaptsev** [comment]
So #13 closes it, right?

**Comment by shershen08** [comment]
yes! thanks for fast reaction!
