### ISSUE TITLE
utf8 charset

### ISSUE THREAD

**Issue by floydback** [vchaptsev/vue-yandex-metrika#16]
https://github.com/vchaptsev/vue-yandex-metrika/blob/83f4dfb737146e2a539dad41d97dbc5372f81953/src/helpers.js#L25

Correct charset name is utf-8

**Comment by KirylSudnikovich** [comment]
@vchaptsev, can you check PR?

**Comment by vchaptsev** [comment]
Fixed in https://github.com/vchaptsev/vue-yandex-metrika/pull/17
New version is released: [1.8.2](https://github.com/vchaptsev/vue-yandex-metrika/pull/17)
