### ISSUE TITLE
Webvisor support

### ISSUE THREAD

**Issue by ohmycto** [vchaptsev/vue-yandex-metrika#2]
Hi and thanks for useful component!

Any plans for supporting Webvisor or any other counter params?

**Comment by vchaptsev** [comment]
Hey, @secoint !
Thanks for the nice words :)

Yes, the support of the webvisor was in my plans.
At first glance, the task seems trivial, I will try to implement support this week

**Comment by vchaptsev** [comment]
Hello, @secoint 
Can you check it now?
