### ISSUE TITLE
Why an error occurs "Cannot read property 'nameMethods' of undefined"?

### ISSUE THREAD

**Issue by EgorKorol** [vchaptsev/vue-yandex-metrika#5]
My main.js:

`import router from './router'
import VueYandexMetrika from 'vue-yandex-metrika'

Vue.use(VueYandexMetrika, {
	id: 46481307,
	env: process.env.NODE_ENV,
	router: router,
	clickmap: true,
	trackLinks: true,
	accurateTrackBounce: true,
	webvisor: true,
	trackHash: true
})`

My components:

`mounted () {
	if (this.isNewUser()) {
		this.$metrika.reachGoal('registration')
	}
}`

Result:

`Error in mounted hook: "TypeError: Cannot read property 'reachGoal' of undefined"`

If you set the timeout, then everything works. How can I fix this?

**Comment by vchaptsev** [comment]
Hey.
I apologize for such a late reply :(
If this is still relevant: checked with the new version, everything works fine.

_____
My code:
```js
mounted() {
  this.$metrika.reachGoal('test-goal')
}
```

If you still have an error (with a new version) and want to fix it, please provide sample repo\fiddle.
