### ISSUE TITLE
Do not work after code updating

### ISSUE THREAD

**Issue by yurahyma** [vchaptsev/vue-yandex-metrika#6]
Hello, I have problem after Yandex updated the Yandex.Metrika counter code. Do not work reachGoal method

**Comment by vchaptsev** [comment]
hey, @yurahyma 
Can you please provide me more info?

Has it worked before?
When did it break?

**Comment by yurahyma** [comment]
Hello
Since 20.06.2018 Yandex changed Metrika counter code, and since that time if I use this plugin I can not track goals in webvisor

**Comment by vchaptsev** [comment]
And what's going on when you are trying to track a goal?
Is there any error?

**Comment by yurahyma** [comment]
Any errors, but information about goals in webvisor do not update

**Comment by vchaptsev** [comment]
Hey.
Sorry for a late reply :(
I updated the version of Metrika, now webvisor works fine.

___
My code: 
```js
Vue.use(VueYandexMetrika, {
  id: 12345678,
  env: 'production',
  options: {webvisor: true},
  router
})
```
