### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by stmegabit** [vchaptsev/vue-yandex-metrika#8]
Hello, thanks for your work. Could you add TypeScript support by adding [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)?

**Comment by vchaptsev** [comment]
Hello, @stmegabit 
It is a good suggestion

I'll try to figure this out in a week, but if you can contribute – it would be great!

**Comment by vchaptsev** [comment]
Let's close it for now 😢
